In [1]:
import pandas as pd

df = pd.read_excel('../data/(數值檔)輕油原料COT分析 2020年.xlsx',index_col=0)
df.index.name = '日期'
v = ['H-'+str(i)+' COT' for i in range(110,200,10)]
df = df.loc[:,v].iloc[1:]
print(df.shape)
df.head()

(52705, 9)

,H-110 COT,H-120 COT,H-130 COT,H-140 COT,H-150 COT,H-160 COT,H-170 COT,H-180 COT,H-190 COT
日期,,,,,,,,,
2020-01-01 00:00:00,824.37,824.76,824.67,237.69,825.08,830.80,814.64,824.68,825.01
2020-01-01 00:10:00,825.28,825.38,825.61,252.83,825.51,834.09,815.16,825.39,825.42
2020-01-01 00:20:00,824.67,824.87,824.47,265.87,824.03,840.08,814.72,824.52,824.96
2020-01-01 00:30:00,823.62,824.49,824.76,275.72,823.62,845.13,814.67,824.05,824.67
2020-01-01 00:40:00,825.00,824.92,825.07,285.64,825.80,845.21,815.50,825.41,825.17

In [2]:
df.to_csv('../data/cleaned_COT_data.csv')
df = pd.read_csv('../data/cleaned_COT_data.csv')
print(df.shape)
df.head()

(52705, 10)

,日期,H-110 COT,H-120 COT,H-130 COT,H-140 COT,H-150 COT,H-160 COT,H-170 COT,H-180 COT,H-190 COT
0,2020-01-01 00:00:00,824.37,824.76,824.67,237.69,825.08,830.80,814.64,824.68,825.01
1,2020-01-01 00:10:00,825.28,825.38,825.61,252.83,825.51,834.09,815.16,825.39,825.42
2,2020-01-01 00:20:00,824.67,824.87,824.47,265.87,824.03,840.08,814.72,824.52,824.96
3,2020-01-01 00:30:00,823.62,824.49,824.76,275.72,823.62,845.13,814.67,824.05,824.67
4,2020-01-01 00:40:00,825.00,824.92,825.07,285.64,825.80,845.21,815.50,825.41,825.17