In [3]:
import pandas as pd

path1 = '../data/(數值檔)輕油原料COT分析2018-2021年 ver3.xlsx'
path2 = '../data/(數值檔)輕油原料COT分析 2020年.xlsx'

def process_cot_data(path):
    df = pd.read_excel(path,index_col=0)
    df.index.name = '日期'
    #v = ['H-'+str(i)+' COT' for i in range(110,200,10)]
    v = df.columns
    df = df.loc[:,v].iloc[1:]
    return df

In [4]:
df1 = process_cot_data(path1)
df1

,Unnamed: 1,T-010A,Unnamed: 3,T-010B,Unnamed: 5,T-015A,Unnamed: 7,T-015B,Unnamed: 9,乙烯產量,...,Unnamed: 57,H-141pass2,H-141 p2 裂解度,Unnamed: 60,H-141pass3,H-141 p3 裂解度,Unnamed: 63,H-141pass4,H-141 p4 裂解度,Unnamed: 66
日期,,,,,,,,,,,,,,,,,,,,,
2018-08-01 00:00:00,2018-08-01 00:10:00,74.0316,72.527,78.064,73.1602,0,0,76.4277,78.3004,89.3988,...,99.1925,798.474,1.42571,88.0578,793.569,1.36772,87.444,785.208,1.33338,86.8515
2018-08-01 00:10:00,2018-08-01 00:20:00,75.0299,73.3242,78.9663,73.804,0,0,77.0575,79.1776,89.3588,...,99.1593,800.997,1.50011,89.265,792.719,1.35554,87.1997,784.76,1.3086,86.3839
2018-08-01 00:20:00,2018-08-01 00:30:00,75.6959,74.0286,79.8368,74.2083,0,0,77.6873,79.6177,89.4674,...,99.2794,798.776,1.40639,87.9006,792.726,1.36186,87.3736,785.146,1.31513,86.5205
2018-08-01 00:30:00,2018-08-01 00:40:00,75.6552,73.8941,79.127,73.7871,0,0,78.3171,80.0579,89.5155,...,99.2794,799.619,1.49908,89.1864,793.043,1.32343,86.6389,784.727,1.26794,85.4935
2018-08-01 00:40:00,2018-08-01 00:50:00,75.6144,73.7596,78.4171,73.184,0,0,78.9469,79.9843,89.477,...,99.1759,801.722,1.44176,88.4157,793.062,1.34385,87.0175,785.037,1.28065,85.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-30 23:10:00,2021-06-30 23:20:00,29.7388,33.3992,31.7836,36.4688,0,23.7188,31.2742,31.6821,11.9343,...,100,26.763,0,100,30.2634,0,100,28.6704,0,100
2021-06-30 23:20:00,2021-06-30 23:30:00,29.7388,33.3861,31.7836,36.4688,0,23.7188,31.2742,31.6848,11.9386,...,100,26.7483,0,100,30.27,0,100,28.6217,0,100
2021-06-30 23:30:00,2021-06-30 23:40:00,29.7388,33.3771,31.7836,36.4688,0,23.7188,31.2742,31.6874,11.9465,...,100,26.7398,0,100,30.243,0,100,28.6132,0,100
2021-06-30 23:40:00,2021-06-30 23:50:00,29.7388,33.3902,31.7836,36.4637,0,23.7188,31.2742,31.6875,11.9462,...,100,26.725,0,100,30.2294,0,100,28.6026,0,100
2021-06-30 23:50:00,2021-07-01 00:00:00,29.7388,33.4033,31.7836,36.4585,0,23.7188,31.2742,31.6875,11.9356,...,100,26.7018,0,100,30.2043,0,100,28.5572,0,100

In [11]:
c1 = ['H-'+str(i)+' COT' for i in range(110,200,10)]
c2 = df1.columns[df1.columns.str.contains('裂解度')].tolist()
df = df1[c1+c2]
df.head()

,H-110 COT,H-120 COT,H-130 COT,H-140 COT,H-150 COT,H-160 COT,H-170 COT,H-180 COT,H-190 COT,H-110 裂解度,...,H-111 裂解度,H-121 裂解度,H-131 p1 裂解度,H-131 p2 裂解度,H-131 p3 裂解度,H-131 p4 裂解度,H-141 p1 裂解度,H-141 p2 裂解度,H-141 p3 裂解度,H-141 p4 裂解度
日期,,,,,,,,,,,,,,,,,,,,,
2018-08-01 00:00:00,820.046,29.8006,820.729,820.601,820.04,819.587,820.273,821.509,820.207,1.13686,...,51.9187,56.0792,0.737323,1.92608,2.538,0.788595,0.955707,1.42571,1.36772,1.33338
2018-08-01 00:10:00,818.147,29.58,818.535,818.693,818.604,816.963,818.849,816.914,819.321,1.13811,...,51.8315,56.2905,0.737323,1.92608,2.49961,0.777962,0.971119,1.50011,1.35554,1.3086
2018-08-01 00:20:00,818.324,29.4944,819.612,819.29,820.808,819.384,819.46,820.119,819.244,1.13711,...,52.2144,56.3386,0.737323,1.92608,2.49418,0.781778,0.975402,1.40639,1.36186,1.31513
2018-08-01 00:30:00,819.605,29.3303,819.858,819.296,819.349,819.066,818.819,818.713,819.159,1.14045,...,52.0147,56.0838,0.737323,1.92608,2.45858,0.779007,0.975402,1.49908,1.32343,1.26794
2018-08-01 00:40:00,821.526,29.457,819.666,820.333,820.627,820.719,819.731,821.596,820.747,1.14185,...,51.7802,56.1674,0.737323,1.92608,2.44642,0.781416,0.973371,1.44176,1.34385,1.28065

In [12]:
df.to_csv('../data/cleaned_COT_data.csv')
df = pd.read_csv('../data/cleaned_COT_data.csv')
print(df.shape)
df.head()

(153360, 29)

,日期,H-110 COT,H-120 COT,H-130 COT,H-140 COT,H-150 COT,H-160 COT,H-170 COT,H-180 COT,H-190 COT,...,H-111 裂解度,H-121 裂解度,H-131 p1 裂解度,H-131 p2 裂解度,H-131 p3 裂解度,H-131 p4 裂解度,H-141 p1 裂解度,H-141 p2 裂解度,H-141 p3 裂解度,H-141 p4 裂解度
0,2018-08-01 00:00:00,820.046387,29.800571,820.729370,820.600525,820.039612,819.586975,820.273438,821.509033,820.206848,...,51.918655,56.079163,0.737323,1.926079,2.538001,0.788595,0.955707,1.425715,1.367721,1.333376
1,2018-08-01 00:10:00,818.146851,29.580025,818.534668,818.692932,818.604431,816.963257,818.849060,816.913757,819.320862,...,51.831528,56.290543,0.737323,1.926079,2.499612,0.777962,0.971119,1.500115,1.355542,1.308600
2,2018-08-01 00:20:00,818.323975,29.494396,819.611572,819.289856,820.808228,819.384216,819.460083,820.118835,819.244202,...,52.214375,56.338554,0.737323,1.926079,2.494183,0.781778,0.975402,1.406393,1.361863,1.315129
3,2018-08-01 00:30:00,819.604675,29.330263,819.857727,819.296204,819.349243,819.066467,818.818909,818.713257,819.158691,...,52.014725,56.083778,0.737323,1.926079,2.458577,0.779007,0.975402,1.499078,1.323431,1.267936
4,2018-08-01 00:40:00,821.526184,29.456963,819.666077,820.332581,820.627075,820.719360,819.730835,821.595703,820.747253,...,51.780170,56.167366,0.737323,1.926079,2.446416,0.781416,0.973371,1.441758,1.343849,1.280648